export {default as About} from './About.jsx'
export {default as Contact} from './Contact.jsx'
export {default as Home} from './Home.jsx'
export {default as PageNotFound} from './PageNotFound.jsx'
export {default as Category} from './Category.jsx'
export {default as Register} from './auth/Register.jsx'
export {default as Login} from './auth/Login.jsx'
export {default as ForgotPassword} from './auth/ForgotPassword.jsx'